using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;
public static class BossModelVerify {
 static int checks;static void Check(bool v,string t){if(!v)throw new Exception(t);checks++;Debug.Log("MODEL_CHECK "+t);}
 public static void Run(){
 foreach(var name in new[]{"BossHappy","BossFrustrated","BossWin","BossLose"}){var p="Assets/Dialogue/"+name;var errors=new System.Collections.Generic.List<string>();var story=new Ink.Compiler(File.ReadAllText(p+".ink"),new Ink.Compiler.Options{errorHandler=(m,t)=>{if(t==Ink.ErrorType.Error)errors.Add(m);}}).Compile();Check(story!=null&&errors.Count==0,"Ink compiles "+name);File.WriteAllText(p+".json",story.ToJson());}
 AssetDatabase.Refresh();var scene=EditorSceneManager.OpenScene("Assets/Scenes/BossFight.unity");var roots=scene.GetRootGameObjects();var table=roots.SelectMany(r=>r.GetComponentsInChildren<Transform>(true)).First(t=>t.name=="Felt hockey table");
 var renderers=table.GetComponentsInChildren<MeshRenderer>(true).Where(r=>r.enabled).ToArray();Check(renderers.Length==69,"69 imported renderers replace disabled temporary shapes");Check(renderers.All(r=>AssetDatabase.GetAssetPath(r.GetComponent<MeshFilter>().sharedMesh)=="Assets/Art/BossFight/BossFight_FeltHockey.fbx"),"All enabled table meshes reference delivered FBX");Check(renderers.All(r=>r.sharedMaterials.All(m=>m&&m.shader.name=="Universal Render Pipeline/Unlit")),"All FBX slots use installed URP materials");Check(renderers.Count(r=>r.sharedMaterial.mainTexture)>2,"Embedded felt and walnut textures assigned");
 var surface=table.Find("BF_FeltBed").GetComponent<MeshRenderer>().bounds;Check(Vector3.Distance(surface.size,new Vector3(6,.2f,10))<.002f&&Mathf.Abs(surface.max.y-1.6f)<.002f,"Y-up 6x10 felt at Y1.6");
 foreach(var end in new[]{"Near","Far"}){var rails=renderers.Where(r=>r.name.StartsWith("BF_EndRail_"+end)).OrderBy(r=>r.bounds.center.x).ToArray();Check(rails.Length==2&&Mathf.Abs(rails[1].bounds.min.x-rails[0].bounds.max.x-2)<.01f,"2m clear end rail opening "+end);}
 var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/BossFight/FeltHockeyTable.prefab");Check(prefab.GetComponentsInChildren<BoxCollider>(true).Length==18,"Original table colliders retained");Check(prefab.GetComponentsInChildren<MeshRenderer>(true).Count(r=>r.enabled)==69,"Reusable prefab uses same 69 FBX visuals");
 var pres=UnityEngine.Object.FindFirstObjectByType<HauntedFish.BossFight.BossCharacterPresentation>();Check(pres&&pres.FishActor&&pres.GhostActor,"Actual authored character and Ink references");Check(!pres.GetComponentsInChildren<Collider>().Any(),"Character proxies cannot obstruct goals or add gameplay bodies");
 var arena=UnityEngine.Object.FindFirstObjectByType<HauntedFish.BossFight.BossArenaManager>();var camera=arena.Camera;camera.gameObject.SetActive(true);var tex=new RenderTexture(1280,720,24);camera.targetTexture=tex;camera.Render();var prior=RenderTexture.active;RenderTexture.active=tex;var image=new Texture2D(1280,720,TextureFormat.RGB24,false);image.ReadPixels(new Rect(0,0,1280,720),0,0);image.Apply();Directory.CreateDirectory("BossModelEvidence");File.WriteAllBytes("BossModelEvidence/01-imported-table-and-characters.png",image.EncodeToPNG());RenderTexture.active=prior;camera.targetTexture=null;UnityEngine.Object.DestroyImmediate(image);UnityEngine.Object.DestroyImmediate(tex);
 File.WriteAllText("BossModelEvidence/result.txt","PASS "+checks+" native FBX/material/geometry/authored presentation checks");EditorApplication.Exit(0);
 }}