using System;
using System.Collections.Generic;
using System.Net;
using System.Security.Cryptography;
using System.Text;

namespace HauntedFish.Multiplayer
{
    // Encode bounded IPv4 TURN messages independently of Unity and the Mirage transport lifecycle.
    public static class TurnProtocol
    {
        // The magic cookie distinguishes STUN control packets from application data.
        public const uint Cookie = 0x2112A442;
        public const ushort Username = 0x0006, Integrity = 0x0008, ErrorCode = 0x0009;
        public const ushort Lifetime = 0x000D, PeerAddress = 0x0012, Data = 0x0013;
        public const ushort Realm = 0x0014, Nonce = 0x0015, RelayedAddress = 0x0016, RequestedTransport = 0x0019;
        // Bound parsing before allocating attributes, even for malformed server responses.
        public const int MaximumMessage = 2048;
        public sealed class Attribute
        {
            public readonly ushort Type;
            public readonly byte[] Value;
            public readonly int Offset;
            public Attribute(ushort type, byte[] value, int offset = 0) { Type = type; Value = value; Offset = offset; }
        }
        public sealed class Message
        {
            public ushort Type;
            public byte[] Transaction;
            public byte[] Wire;
            public readonly List<Attribute> Attributes = new List<Attribute>();
            public Attribute Find(ushort type) => Attributes.Find(a => a.Type == type);
        }
        // Network byte order is explicit so Windows and Linux generate identical frames.
        public static int Read16(byte[] b, int i) => (b[i] << 8) | b[i + 1];
        static void Write16(byte[] b, int i, int v) { b[i] = (byte)(v >> 8); b[i + 1] = (byte)v; }
        public static byte[] Number(uint value) => new[] { (byte)(value >> 24), (byte)(value >> 16), (byte)(value >> 8), (byte)value };
        public static uint Read32(byte[] b, int i) => ((uint)b[i] << 24) | ((uint)b[i + 1] << 16) | ((uint)b[i + 2] << 8) | b[i + 3];
        public static Attribute Text(ushort type, string value) => new Attribute(type, Encoding.UTF8.GetBytes(value));
        // TURN long-term authentication uses a credential-derived key, never the server REST secret.
        public static byte[] Key(string username, string realm, string password)
        {
            using (var md5 = MD5.Create()) return md5.ComputeHash(Encoding.UTF8.GetBytes(username + ":" + realm + ":" + password));
        }
        public static byte[] Transaction()
        {
            var id = new byte[12];
            using (var random = RandomNumberGenerator.Create()) random.GetBytes(id);
            return id;
        }
        public static byte[] Encode(ushort type, byte[] transaction, IList<Attribute> attributes, byte[] key = null)
        {
            // Account for padded attributes and the final integrity attribute before allocating.
            if (transaction == null || transaction.Length != 12 || (type & 0xC000) != 0) throw new ArgumentException("Invalid STUN header.");
            int size = 20 + (key == null ? 0 : 24);
            foreach (var a in attributes)
            {
                if (a.Value == null || a.Type == Integrity) throw new ArgumentException("Integrity must be generated by the encoder.");
                size = checked(size + 4 + ((a.Value.Length + 3) & ~3));
            }
            if (size > MaximumMessage) throw new ArgumentException("TURN message exceeds its bound.");
            var wire = new byte[size];
            Write16(wire, 0, type); Write16(wire, 2, size - 20);
            Buffer.BlockCopy(Number(Cookie), 0, wire, 4, 4); Buffer.BlockCopy(transaction, 0, wire, 8, 12);
            int offset = 20;
            foreach (var a in attributes)
            {
                Write16(wire, offset, a.Type); Write16(wire, offset + 2, a.Value.Length);
                Buffer.BlockCopy(a.Value, 0, wire, offset + 4, a.Value.Length);
                offset += 4 + ((a.Value.Length + 3) & ~3);
            }
            if (key != null)
            {
                // The HMAC input excludes the integrity attribute while header length includes it.
                Write16(wire, offset, Integrity); Write16(wire, offset + 2, 20);
                using (var hmac = new HMACSHA1(key)) Buffer.BlockCopy(hmac.ComputeHash(wire, 0, offset), 0, wire, offset + 4, 20);
            }
            return wire;
        }
        public static bool TryParse(byte[] wire, out Message message)
        {
            message = null;
            if (wire == null || wire.Length < 20 || wire.Length > MaximumMessage || (wire[0] & 0xC0) != 0 || Read32(wire, 4) != Cookie) return false;
            int size = Read16(wire, 2);
            if ((size & 3) != 0 || size != wire.Length - 20) return false;
            var result = new Message { Type = (ushort)Read16(wire, 0), Transaction = new byte[12], Wire = (byte[])wire.Clone() };
            Buffer.BlockCopy(wire, 8, result.Transaction, 0, 12);
            var seen = new HashSet<ushort>();
            for (int offset = 20; offset < wire.Length;)
            {
                if (wire.Length - offset < 4) return false;
                ushort type = (ushort)Read16(wire, offset);
                int length = Read16(wire, offset + 2), padded = (length + 3) & ~3;
                if (padded > wire.Length - offset - 4 || !seen.Add(type)) return false;
                // Nothing after integrity may change the meaning of an authenticated response.
                if (seen.Contains(Integrity) && type != Integrity && type != 0x8028) return false;
                var value = new byte[length]; Buffer.BlockCopy(wire, offset + 4, value, 0, length);
                result.Attributes.Add(new Attribute(type, value, offset)); offset += 4 + padded;
            }
            message = result; return true;
        }
        public static bool Verify(Message message, byte[] key)
        {
            var attribute = message.Find(Integrity);
            if (attribute == null || attribute.Value.Length != 20 || key == null) return false;
            // RFC integrity calculation temporarily truncates header length at MESSAGE-INTEGRITY.
            var prefix = new byte[attribute.Offset]; Buffer.BlockCopy(message.Wire, 0, prefix, 0, prefix.Length);
            Write16(prefix, 2, attribute.Offset + 24 - 20);
            byte[] expected;
            using (var hmac = new HMACSHA1(key)) expected = hmac.ComputeHash(prefix);
            int difference = 0; for (int i = 0; i < 20; i++) difference |= expected[i] ^ attribute.Value[i];
            return difference == 0;
        }
        public static Attribute Address(ushort type, IPEndPoint endpoint)
        {
            var ip = endpoint.Address.GetAddressBytes();
            if (ip.Length != 4 || endpoint.Port < 1) throw new ArgumentException("Only IPv4 relay endpoints are supported.");
            var value = new byte[8]; value[1] = 1; Write16(value, 2, endpoint.Port ^ (int)(Cookie >> 16));
            var mask = Number(Cookie); for (int i = 0; i < 4; i++) value[4 + i] = (byte)(ip[i] ^ mask[i]);
            return new Attribute(type, value);
        }
        public static IPEndPoint DecodeAddress(Attribute attribute)
        {
            if (attribute == null || attribute.Value.Length != 8 || attribute.Value[0] != 0 || attribute.Value[1] != 1) throw new FormatException("Invalid IPv4 XOR address.");
            var ip = new byte[4]; var mask = Number(Cookie);
            for (int i = 0; i < 4; i++) ip[i] = (byte)(attribute.Value[4 + i] ^ mask[i]);
            int port = Read16(attribute.Value, 2) ^ (int)(Cookie >> 16);
            if (port == 0) throw new FormatException("Invalid relay port.");
            return new IPEndPoint(new IPAddress(ip), port);
        }
    }
}
